### ISSUE TITLE
[ISSUE] Pypechain crashes when used on `IMorpho.sol`

### ISSUE THREAD

**Issue by slundqui** [delvtech/pypechain#116]
I get the following error when running pypechain on morpho's contract https://github.com/morpho-org/morpho-blue/blob/55d2d99304fb3fb930c688462ae2ccabb1d533ad/src/interfaces/IMorpho.sol

```
Traceback (most recent call last):
  File "/Users/slundquist/workspace/agent0/.venv/bin/pypechain", line 8, in <module>
    sys.exit(main())
  File "/Users/slundquist/workspace/agent0/.venv/lib/python3.10/site-packages/pypechain/main.py", line 27, in main
    pypechain(abi_file_path, output_dir, line_length, apply_formatting)
  File "/Users/slundquist/workspace/agent0/.venv/lib/python3.10/site-packages/pypechain/main.py", line 67, in pypechain
    file_names: list[str] = render_files(abi_infos, output_dir, line_length, apply_formatting)
  File "/Users/slundquist/workspace/agent0/.venv/lib/python3.10/site-packages/pypechain/render/main.py", line 38, in render_files
    contract_infos = get_contract_infos(abi_infos)
  File "/Users/slundquist/workspace/agent0/.venv/lib/python3.10/site-packages/pypechain/render/contract.py", line 69, in get_contract_infos
    structs = get_structs_for_abi(abi_info.abi)
  File "/Users/slundquist/workspace/agent0/.venv/lib/python3.10/site-packages/pypechain/utilities/abi.py", line 386, in get_structs_for_abi
    input_structs = get_structs(fn_inputs, structs)
  File "/Users/slundquist/workspace/agent0/.venv/lib/python3.10/site-packages/pypechain/utilities/abi.py", line 324, in get_structs
    struct_name = get_struct_name(param)
  File "/Users/slundquist/workspace/agent0/.venv/lib/python3.10/site-packages/pypechain/utilities/abi.py", line 556, in get_struct_name
    struct_name = internal_type.split(".")[1].rstrip("[]")
IndexError: list index out of range
```

**Comment by dpaiton** [comment]
resolved by #119
