### ISSUE TITLE
[ISSUE] Package does not work as expected

### ISSUE THREAD

**Issue by zarifpour** [delvtech/pypechain#87]
I have tried running it several times on different abis, including the Example.json which worked with some error:

```
❯ pypechain abi/Example.json
WARNING:root:Unknown Solidity type: InnerStruct
WARNING:root:Unknown Solidity type: InnerStruct
WARNING:root:Unknown Solidity type: InnerStruct
WARNING:root:Unknown Solidity type: InnerStruct
WARNING:root:Unknown Solidity type: InnerStruct
WARNING:root:Unknown Solidity type: InnerStruct
WARNING:root:Unknown Solidity type: InnerStruct
WARNING:root:Unknown Solidity type: InnerStruct
WARNING:root:Unknown Solidity type: InnerStruct
WARNING:root:Unknown Solidity type: InnerStruct
autoflake --remove-all-unused-imports pypechain_types/ExampleContract.py
/bin/sh: autoflake: command not found
Error creating types for abi/Example.json
Traceback (most recent call last):
  File "/Users/daniel.zarifpour/rebalance_bot/.venv/bin/pypechain", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/daniel.zarifpour/rebalance_bot/.venv/lib/python3.11/site-packages/pypechain/main.py", line 60, in main
    raise err
  File "/Users/daniel.zarifpour/rebalance_bot/.venv/lib/python3.11/site-packages/pypechain/main.py", line 53, in main
    rendered_file_names = render_files(str(json_file), output_dir, line_length)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/daniel.zarifpour/rebalance_bot/.venv/lib/python3.11/site-packages/pypechain/render/main.py", line 31, in render_files
    format_file(contract_file_path, line_length)
  File "/Users/daniel.zarifpour/rebalance_bot/.venv/lib/python3.11/site-packages/pypechain/utilities/format.py", line 124, in format_file
    subprocess.run(f"autoflake --in-place --remove-all-unused-imports {file_path}", shell=True, check=True)
  File "/Users/daniel.zarifpour/.pyenv/versions/3.11.5/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'autoflake --in-place --remove-all-unused-imports pypechain_types/ExampleContract.py' returned non-zero exit status 127.
```

---

For other abis, it seems impossible to run.

```
❯ pypechain abi/RebalanceContractMock.json
Error creating types for abi/RebalanceContractMock.json
Traceback (most recent call last):
  File "/Users/daniel.zarifpour/rebalance_bot/.venv/bin/pypechain", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/daniel.zarifpour/rebalance_bot/.venv/lib/python3.11/site-packages/pypechain/main.py", line 60, in main
    raise err
  File "/Users/daniel.zarifpour/rebalance_bot/.venv/lib/python3.11/site-packages/pypechain/main.py", line 53, in main
    rendered_file_names = render_files(str(json_file), output_dir, line_length)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/daniel.zarifpour/rebalance_bot/.venv/lib/python3.11/site-packages/pypechain/render/main.py", line 23, in render_files
    rendered_contract_code = render_contract_file(contract_name, file_path)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/daniel.zarifpour/rebalance_bot/.venv/lib/python3.11/site-packages/pypechain/render/contract.py", line 51, in render_contract_file
    abi, bytecode = load_abi_from_file(abi_file_path)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/daniel.zarifpour/rebalance_bot/.venv/lib/python3.11/site-packages/pypechain/utilities/abi.py", line 449, in load_abi_from_file
    abi = get_abi_from_json(json_file)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/daniel.zarifpour/rebalance_bot/.venv/lib/python3.11/site-packages/pypechain/utilities/abi.py", line 704, in get_abi_from_json
    raise ValueError("Unable to identify an ABI for the given JSON.")
ValueError: Unable to identify an ABI for the given JSON.
```

Also, when I try running as a standalone file (as provided in the README, it is impossible to fix this error.

```
usage: pychain.py [-h] [--output_dir OUTPUT_DIR]
                  [--line_length LINE_LENGTH]
                  abi_file_path
pychain.py: error: the following arguments are required: abi_file_path
```
---

It also seems it's not installing as expected as I had to manually install iSort and in Example.json it's complaining about autoflake.

**Comment by dpaiton** [comment]
Thanks for alerting us to this @zarifpour! We will look into it and report back.

**Comment by sentilesdal** [comment]
@zarifpour I believe the issues have been fixed now.  

pip installation:
We had to make some dependencies like isort and autoflake required.  We also bumped the version of python to 3.11.  It should install correctly from pip now.  

using in a python script:
I updated pypechain to export an improved version of the script, so now you can use it like this:
```python
from pypechain import pypechain

abi_dir = "./abis"
out_dir = "./types"
line_length = 80
pypechain(abi_dir, out_dir, line_length)
```

NOTE: that I've only tested on json from solidity files compiled with `solc` and `foundry`.  If you are using something else, let me know and I can add support.

I'll leave this issue open for a while, if you have time try it out.	I'll close next week if we don't hear anything.

**Comment by dpaiton** [comment]
Closing due to inactivity
